<?php
declare(strict_types=1);
namespace App\Services;
use App\Repositories\ThumbnailRepository;
use App\Repositories\PublicationPreparationRepository;
use App\Media\Thumbnails\PublicationMetadata;
use App\Media\Thumbnails\PublicationVersionConflict;
use PDO;
final class PublicationPreparationService
{
 public function __construct(private PDO $pdo,private PublicationPreparationRepository $repository,private ThumbnailRepository $thumbnails) {}
 public function findOwned(int $id,int $userId): ?array { return $this->repository->findOwned($id,$userId); }
 public function forClip(int $clipId,int $userId): array { return $this->repository->forClip($clipId,$userId); }
 public function history(int $id,int $userId): array { return $this->repository->history($id,$userId); }
 public function save(int $clipId,int $userId,int $id,int $version,array $metadata,?int $thumbnailId): ?int { $metadata=PublicationMetadata::normalize($metadata);return $this->transaction(function()use($clipId,$userId,$id,$version,$metadata,$thumbnailId){$clip=$this->thumbnails->sourceOwned($clipId,$userId,true);if(!$clip)return null;$old=$id>0?$this->repository->findOwned($id,$userId):null;if($id>0&&(!$old||(int)$old['clip_id']!==$clipId))return null;if(($old&&(int)$old['version']!==$version)||(!$old&&$version!==0))throw new PublicationVersionConflict('Atualize a preparação antes de salvar.');if($old&&$old['status']==='archived')throw new \InvalidArgumentException('Preparação arquivada.');$this->validateThumbnail($thumbnailId,$clipId,$userId);return $this->repository->persist($id,$userId,$version,['clip_id'=>$clipId,'render_revision'=>$clip['render_revision'],'thumbnail_id'=>$thumbnailId,'metadata'=>$metadata,'status'=>'draft']);}); }
 public function transition(int $id,int $userId,int $version,string $status): ?int { if(!in_array($status,PublicationMetadata::STATES,true))throw new \InvalidArgumentException('Estado inválido.');return $this->transaction(function()use($id,$userId,$version,$status){$old=$this->repository->findOwned($id,$userId);if(!$old)return null;if((int)$old['version']!==$version)throw new PublicationVersionConflict('Esta preparação mudou. Atualize a página.');$allowed=['draft'=>['ready','archived'],'ready'=>['draft','exported','marked_published','archived'],'exported'=>['draft','ready','marked_published','archived'],'marked_published'=>['draft','archived'],'archived'=>[]];if(!in_array($status,$allowed[$old['status']]??[],true))throw new \InvalidArgumentException('Transição de estado inválida.');if($status!=='archived')$this->assertAvailable($old,$userId);$old['status']=$status;return $this->repository->persist($id,$userId,$version,$old);}); }
 public function package(int $id,int $userId,string $format): ?string { if(!in_array($format,['json','txt'],true))throw new \InvalidArgumentException('Formato inválido.');$r=$this->findOwned($id,$userId);if(!$r||!in_array($r['status'],['ready','exported','marked_published'],true))return null;try{$this->assertAvailable($r,$userId);}catch(\InvalidArgumentException){return null;}$p=$r['metadata']+['clip_id'=>(int)$r['clip_id'],'publication_id'=>$id,'version'=>(int)$r['version'],'status'=>$r['status'],'publication_confirmation'=>$r['status']==='marked_published'?'manual':'not_confirmed','video_download'=>'/clips/'.$r['clip_id'].'/download','thumbnail_download'=>$r['thumbnail_id']?'/thumbnails/'.$r['thumbnail_id'].'/download':'/clips/'.$r['clip_id'].'/thumbnail','links_require_authenticated_owner'=>true];if($format==='json')return json_encode($p,JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT);$lines=[];foreach($p as $k=>$v)$lines[]=$k.': '.(is_array($v)?implode(' ',$v):(string)$v);return implode("\n\n",$lines)."\n"; }
 private function validateThumbnail(?int $id,int $clipId,int $userId): void { if($id===null)return;$t=$this->thumbnails->findOwned($id,$userId);if(!$t||(int)$t['clip_id']!==$clipId||$t['status']!=='ready'||empty($t['object_key']))throw new \InvalidArgumentException('Selecione uma capa pronta deste clipe.'); }
 private function assertAvailable(array $r,int $userId): void { $c=$this->thumbnails->sourceOwned((int)$r['clip_id'],$userId,true);if(!$c||(int)$c['render_revision']!==(int)$r['render_revision'])throw new \InvalidArgumentException('O vídeo desta preparação não está disponível.');$this->validateThumbnail($r['thumbnail_id']===null?null:(int)$r['thumbnail_id'],(int)$r['clip_id'],$userId); }
 private function transaction(callable $f): mixed { $this->pdo->beginTransaction();try{$r=$f();$this->pdo->commit();return $r;}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;} }
}
