<?php
declare(strict_types=1);
use App\Core\Csrf;
use App\Media\Thumbnails\PublicationMetadata;
$id=(int)$clip['id'];$labels=['draft'=>'Rascunho','ready'=>'Pronta para exportar','exported'=>'Pacote exportado','marked_published'=>'Publicação informada manualmente','archived'=>'Arquivada'];$new=['id'=>0,'version'=>0,'status'=>'draft','thumbnail_id'=>null,'metadata'=>PublicationMetadata::normalize(['title'=>$clip['title']]),'history'=>[]];ob_start();?>
<link rel="stylesheet" href="/assets/css/thumbnail-studio.css"><section class="publication-page"><nav><a href="/clips/<?= $id ?>/editar">Editor</a> · <a href="/clips/<?= $id ?>/capas">Estúdio de capas</a></nav><h2><?= e($clip['title']) ?></h2><p>Prepare os textos e a capa para cada plataforma. As marcações e o histórico são locais. “Publicação informada manualmente” registra sua confirmação.</p>
<?php if($error):?><p role="alert" class="studio-error"><?= e($error) ?></p><?php endif;?>
<?php foreach(array_merge([$new],$publications) as $publication):$pid=(int)$publication['id'];$recovered=isset($draft)&&$draft['id']===$pid?$draft:null;$meta=$recovered['metadata']??$publication['metadata'];$formVersion=$recovered['version']??(string)$publication['version'];$formThumbnail=$recovered['thumbnail_id']??(string)($publication['thumbnail_id']??0);?><article id="publicacao-<?= $pid ?>" class="publication-card"><h3><?= $pid?'Preparação #'.$pid:'Nova preparação' ?></h3><p><?= e($labels[$publication['status']]) ?><?= $pid?' · versão '.(int)$publication['version']:'' ?></p>
<?php if($recovered):?><p role="status">Seu rascunho foi mantido neste formulário e não foi salvo.<?php if($recovered['conflict']):?> Conflito — versão enviada: <?= e($formVersion) ?>; versão salva: <?= (int)$publication['version'] ?>. Copie seu texto e revise a versão salva antes de enviar novamente. <a href="/clips/<?= $id ?>/publicacao#publicacao-<?= $pid ?>" target="_blank" rel="noopener">Abrir versão salva em outra aba</a><?php endif;?></p><?php endif;?>
<?php if($publication['status']!=='archived'||$recovered):?><form method="post" action="/clips/<?= $id ?>/publicacao"><input type="hidden" name="_token" value="<?= e(Csrf::token()) ?>"><input type="hidden" name="publication_id" value="<?= $pid ?>"><input type="hidden" name="version" value="<?= e($formVersion) ?>"><div class="studio-fields">
<label>Plataforma<select name="platform"><?php if(!in_array($meta['platform'],PublicationMetadata::PLATFORMS,true)):?><option value="<?= e($meta['platform']) ?>" selected>Plataforma enviada inválida: <?= e($meta['platform']) ?></option><?php endif;?><?php foreach(['youtube'=>'YouTube','youtube_shorts'=>'YouTube Shorts','instagram'=>'Instagram','tiktok'=>'TikTok','facebook'=>'Facebook'] as $v=>$label):?><option value="<?= $v ?>" <?= $meta['platform']===$v?'selected':'' ?>><?= $label ?></option><?php endforeach;?></select></label>
<label>Capa<select name="thumbnail_id"><?php $readyIds=['0'];foreach($thumbnails as $t)if($t['status']==='ready')$readyIds[]=(string)$t['id'];if(!in_array($formThumbnail,$readyIds,true)):?><option value="<?= e($formThumbnail) ?>" selected>Capa enviada indisponível; selecione outra</option><?php endif;?><option value="0" <?= $formThumbnail==='0'?'selected':'' ?>>Original do clipe</option><?php foreach($thumbnails as $t):if($t['status']!=='ready')continue;?><option value="<?= (int)$t['id'] ?>" <?= $formThumbnail===(string)$t['id']?'selected':'' ?>>Capa <?= (int)$t['id'] ?> · <?= e((string)$t['offset_seconds']) ?> s</option><?php endforeach;?></select></label>
<?php foreach(['title'=>['Título',255],'description'=>['Descrição',5000],'caption'=>['Legenda da postagem',2200],'cta'=>['Chamada para ação',500]] as $key=>[$label,$max]):?><label><?= $label ?><textarea name="<?= $key ?>" maxlength="<?= $max ?>" rows="<?= $key==='description'?4:2 ?>"><?= e($meta[$key]) ?></textarea></label><?php endforeach;?>
<label>Hashtags (até 30)<textarea name="hashtags" rows="2"><?= e(is_array($meta['hashtags'])?implode(' ',$meta['hashtags']):$meta['hashtags']) ?></textarea></label></div><button type="submit">Salvar rascunho</button></form><?php endif;?>
<?php if($pid&&$publication['status']!=='archived'):?><form method="post" action="/publicacoes/<?= $pid ?>/status" class="publication-state"><input type="hidden" name="_token" value="<?= e(Csrf::token()) ?>"><input type="hidden" name="version" value="<?= (int)$publication['version'] ?>"><label>Atualizar estado<select name="status"><?php $states=['draft'=>['ready','archived'],'ready'=>['draft','exported','marked_published','archived'],'exported'=>['draft','ready','marked_published','archived'],'marked_published'=>['draft','archived']];foreach($states[$publication['status']]??[] as $state):?><option value="<?= $state ?>"><?= e($labels[$state]) ?></option><?php endforeach;?></select></label><button type="submit">Registrar estado</button></form><?php endif;?>
<?php if(in_array($publication['status'],['ready','exported','marked_published'],true)):?><p><a href="/publicacoes/<?= $pid ?>/download?format=json">Baixar pacote JSON</a> · <a href="/publicacoes/<?= $pid ?>/download?format=txt">Baixar pacote TXT</a> · <a href="/clips/<?= $id ?>/download">Baixar vídeo</a></p><?php endif;?>
<?php if($pid):?><details><summary>Histórico local (<?= count($publication['history']) ?> registros)</summary><ol><?php foreach($publication['history'] as $event):?><li>Versão <?= (int)$event['version'] ?> · <?= e($labels[$event['status']]??$event['status']) ?> · <?= e($event['created_at']) ?></li><?php endforeach;?></ol></details><?php endif;?></article><?php endforeach;?>
<p>Os links dos pacotes exigem login da conta proprietária. Baixar o pacote não envia conteúdo para as plataformas.</p></section>
<?php $content=(string)ob_get_clean();require __DIR__.'/../layouts/app.php'; ?>
