<?php
declare(strict_types=1);
use App\Billing\{BillingReconciliationService,BillingRepository,BillingWebhookProcessor,CheckoutService,CouponService,CurlHttpTransport,FinancialRepository,GatewaySettingsService,HttpTransport,SubscriptionService};
use App\Controllers\{BillingAdminController,BillingController,BillingWebhookController}; use App\Core\{Database,Env,Request,Router,View}; use App\Security\SecretCipher; use App\Services\RateLimiter;
return static function(Router $router,array $deps):void {
 $auth=$deps['authenticated']??null;$admin=$deps['admin_only']??null;if($auth===null||$admin===null)throw new \InvalidArgumentException('Billing requires access middleware.');
 $pdoFactory=isset($deps['pdo_factory'])&&is_callable($deps['pdo_factory'])?$deps['pdo_factory']:static fn():\PDO=>($deps['pdo']??Database::connection());
 $viewFactory=isset($deps['view_factory'])&&is_callable($deps['view_factory'])?$deps['view_factory']:static fn():View=>($deps['view']??new View());
 $cipherFactory=isset($deps['cipher_factory'])&&is_callable($deps['cipher_factory'])?$deps['cipher_factory']:static fn():SecretCipher=>($deps['cipher']??new SecretCipher((string)Env::get('APP_ENCRYPTION_KEY','')));
 $transportFactory=isset($deps['transport_factory'])&&is_callable($deps['transport_factory'])?$deps['transport_factory']:static fn():HttpTransport=>($deps['transport']??new CurlHttpTransport());
 $browserFactory=static function()use($deps,$pdoFactory,$viewFactory,$cipherFactory,$transportFactory):BillingController {static $controller=null;if($controller)return $controller;$pdo=$pdoFactory();$repo=new BillingRepository($pdo);$settings=new GatewaySettingsService($pdo,$cipherFactory());$transport=$transportFactory();$profile=$deps['user_profile']??static function(int $id)use($pdo):?array{$s=$pdo->prepare('SELECT u.id,u.name,u.email,u.credits,p.name AS plan_name FROM users u LEFT JOIN plans p ON p.id=u.plan_id WHERE u.id=?');$s->execute([$id]);return $s->fetch(\PDO::FETCH_ASSOC)?:null;};$emitter=$deps['communication_emitter']??null;$controller=new BillingController($viewFactory(),$repo,new CheckoutService($repo,$settings,$transport,(string)($deps['return_base']??Env::get('APP_URL','http://127.0.0.1:8088'))),$settings,new CouponService($repo),new SubscriptionService($repo,$settings,$transport,$emitter),new BillingReconciliationService($repo,$settings,$transport,$emitter),$profile,(string)($deps['provider']??'stripe'),(string)($deps['environment']??'production'));return $controller;};
 $adminFactory=static function()use($deps,$pdoFactory,$viewFactory,$cipherFactory):BillingAdminController {static $controller=null;if($controller)return $controller;$pdo=$pdoFactory();$identity=$deps['admin_identity']??static function(int $id)use($pdo):?array{$s=$pdo->prepare('SELECT name,email FROM users WHERE id=?');$s->execute([$id]);return $s->fetch(\PDO::FETCH_ASSOC)?:null;};$repo=new BillingRepository($pdo);$controller=new BillingAdminController($viewFactory(),new FinancialRepository($pdo),new GatewaySettingsService($pdo,$cipherFactory()),new CouponService($repo),$pdo,$identity);return $controller;};
 $webhookFactory=static function()use($deps,$pdoFactory,$cipherFactory,$transportFactory):BillingWebhookController {static $controller=null;if($controller)return $controller;$pdo=$pdoFactory();$repo=new BillingRepository($pdo);$settings=new GatewaySettingsService($pdo,$cipherFactory());$processor=$deps['webhook_processor']??new BillingWebhookProcessor($repo,$settings,$transportFactory(),$deps['communication_emitter']??null);$process=is_callable($processor)?$processor:static fn(string $p,string $e,string $body,string $auth):array=>$processor->process($p,$e,$body,$auth);$limit=$deps['webhook_rate_limit']??static fn(string $p,string $ip):bool=>(new RateLimiter($pdo))->hit('billing_webhook_'.$p,$ip,30,60);$controller=new BillingWebhookController($process,$limit);return $controller;};
 $router->get('/checkout/plano/{plan}',static fn(Request $r,array $p)=>$browserFactory()->review($r,$p),[$auth]);$router->post('/checkout/{plan}',static fn(Request $r,array $p)=>$browserFactory()->start($r,$p),[$auth]);$router->get('/checkout/retorno/{attempt}',static fn(Request $r,array $p)=>$browserFactory()->returned($r,$p),[$auth]);$router->get('/checkout/{attempt}/status',static fn(Request $r,array $p)=>$browserFactory()->status($r,$p),[$auth]);$router->post('/checkout/{attempt}/reconciliar',static fn(Request $r,array $p)=>$browserFactory()->reconcile($r,$p),[$auth]);$router->get('/conta/pagamentos',static fn(Request $r)=>$browserFactory()->history($r),[$auth]);$router->post('/conta/assinaturas/{id}/cancelar',static fn(Request $r,array $p)=>$browserFactory()->cancel($r,$p),[$auth]);
 $router->get('/admin/financeiro',static fn(Request $r)=>$adminFactory()->finance($r),[$admin]);$router->get('/admin/gateways',static fn(Request $r)=>$adminFactory()->gateways($r),[$admin]);$router->post('/admin/gateways/{provider}/{environment}',static fn(Request $r,array $p)=>$adminFactory()->saveGateway($r,$p),[$admin]);$router->get('/admin/cupons',static fn(Request $r)=>$adminFactory()->coupons($r),[$admin]);$router->post('/admin/cupons',static fn(Request $r)=>$adminFactory()->saveCoupon($r),[$admin]);$router->post('/admin/cupons/{id}',static fn(Request $r,array $p)=>$adminFactory()->saveCoupon($r,$p),[$admin]);
 $router->webhookPost('/webhooks/stripe/{environment}',static fn(Request $r,array $p)=>$webhookFactory()->stripe($r,$p));$router->webhookPost('/webhooks/pagarme/{environment}/{token}',static fn(Request $r,array $p)=>$webhookFactory()->pagarme($r,$p));
};
