<?php
declare(strict_types=1);
namespace App\Communications;
use App\Security\SecretCipher; use DateTimeImmutable; use InvalidArgumentException; use PDO; use PDOException; use Throwable;
final class CampaignService {
    private const AAD='clipforge:communications:v1'; private \Closure $clock;
    public function __construct(private PDO $pdo,private SecretCipher $cipher,private CampaignUnsubscribeService $unsubscribe,?callable $clock=null){$this->clock=$clock===null?static fn():DateTimeImmutable=>new DateTimeImmutable('now'):\Closure::fromCallable($clock);}
    public function create(int $actor,array $input):int { $this->assertActor($actor);$data=$this->data($input);$template=$this->template($data['template_id']);$snapshot=$this->cipher->encrypt(json_encode(['subject_template'=>$template['subject_template'],'html_template'=>$template['html_template'],'text_template'=>$template['text_template'],'template_version'=>(int)$template['version']],JSON_THROW_ON_ERROR),self::AAD);$s=$this->pdo->prepare("INSERT INTO communication_campaigns(name,template_id,title,body,segment,plan_id,status,scheduled_at,template_snapshot_ciphertext,recipient_cursor,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?, 'draft',NULL,?,0,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");$s->execute([$data['name'],$data['template_id'],$data['title'],$data['body'],$data['segment'],$data['plan_id'],$snapshot,$actor]);return (int)$this->pdo->lastInsertId(); }
    public function update(int $actor,int $id,array $input):void {$this->assertActor($actor);$data=$this->data($input);$template=$this->template($data['template_id']);$snapshot=$this->cipher->encrypt(json_encode(['subject_template'=>$template['subject_template'],'html_template'=>$template['html_template'],'text_template'=>$template['text_template'],'template_version'=>(int)$template['version']],JSON_THROW_ON_ERROR),self::AAD);$s=$this->pdo->prepare("UPDATE communication_campaigns SET name=?,template_id=?,title=?,body=?,segment=?,plan_id=?,template_snapshot_ciphertext=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='draft'");$s->execute([$data['name'],$data['template_id'],$data['title'],$data['body'],$data['segment'],$data['plan_id'],$snapshot,$id]);if($s->rowCount()!==1)throw new InvalidArgumentException('Apenas rascunhos podem ser alterados.');}
    public function schedule(int $actor,int $id,DateTimeImmutable $at):void {$this->assertActor($actor);$s=$this->pdo->prepare("UPDATE communication_campaigns SET status='scheduled',scheduled_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='draft'");$s->execute([$at->format('Y-m-d H:i:s'),$id]);if($s->rowCount()!==1)throw new InvalidArgumentException('Apenas rascunhos podem ser agendados.');}
    public function cancel(int $actor,int $id):void {$this->assertActor($actor);$this->pdo->beginTransaction();try{$now=($this->clock)()->format('Y-m-d H:i:s');$this->pdo->prepare("UPDATE communication_campaigns SET status='cancelled',cancelled_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status IN ('draft','scheduled','processing','completed')")->execute([$now,$id]);$this->pdo->prepare("UPDATE communication_campaign_recipients SET status='skipped' WHERE campaign_id=? AND status IN ('pending','queued')")->execute([$id]);$this->pdo->prepare("UPDATE communication_email_outbox SET status='cancelled',payload_ciphertext=NULL WHERE dedupe_key LIKE ? AND (status IN ('pending','retry') OR (status='leased' AND leased_until<=?))")->execute(['campaign:'.$id.':%',$now]);$this->pdo->commit();}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
    public function queueBatch(int $id,int $limit=100):int {$limit=max(1,min(100,$limit));$this->pdo->beginTransaction();try{$campaign=$this->campaign($id,true);if(!in_array($campaign['status'],['scheduled','processing'],true)||($campaign['scheduled_at']!==null&&$campaign['scheduled_at']>($this->clock)()->format('Y-m-d H:i:s'))){$this->pdo->commit();return 0;}$this->pdo->prepare("UPDATE communication_campaigns SET status='processing',lease_until=? WHERE id=?")->execute([($this->clock)()->modify('+60 seconds')->format('Y-m-d H:i:s'),$id]);$rows=$this->eligible($campaign,$limit);if($rows===[]){$this->pdo->prepare("UPDATE communication_campaigns SET status='completed',completed_at=?,lease_until=NULL WHERE id=? AND status='processing'")->execute([($this->clock)()->format('Y-m-d H:i:s'),$id]);$this->pdo->commit();return 0;}$snapshot=json_decode($this->cipher->decrypt((string)$campaign['template_snapshot_ciphertext'],self::AAD),true,16,JSON_THROW_ON_ERROR);$queued=0;$cursor=(int)$campaign['recipient_cursor'];foreach($rows as $row){$cursor=max($cursor,(int)$row['id']);$key='campaign:'.$id.':user:'.(int)$row['id'];$this->recipient($id,$row);$payload=['event'=>'marketing.campaign','variables'=>['nome_usuario'=>(string)$row['name'],'titulo'=>(string)$campaign['title'],'conteudo'=>(string)$campaign['body']],'template_snapshot'=>$snapshot,'unsubscribe_url'=>$this->unsubscribe->urlFor((int)$row['id'])];try{$this->pdo->prepare("INSERT INTO communication_email_outbox(user_id,recipient,event,category,payload_ciphertext,dedupe_key,status,available_at) VALUES(?,?, 'marketing.campaign','marketing',?,?, 'pending',?)")->execute([(int)$row['id'],(string)$row['email'],$this->cipher->encrypt(json_encode($payload,JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),self::AAD),$key,($this->clock)()->format('Y-m-d H:i:s')]);$this->pdo->prepare("UPDATE communication_campaign_recipients SET status='queued',queued_at=? WHERE campaign_id=? AND user_id=?")->execute([($this->clock)()->format('Y-m-d H:i:s'),$id,$row['id']]);$queued++;}catch(PDOException $e){if(!str_contains($e->getMessage(),'UNIQUE constraint failed')&&(int)($e->errorInfo[1]??0)!==1062)throw $e;}}$this->pdo->prepare('UPDATE communication_campaigns SET recipient_cursor=?,lease_until=NULL WHERE id=?')->execute([$cursor,$id]);$this->pdo->commit();return $queued;}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
    public function due(int $limit=10):int {$s=$this->pdo->prepare("SELECT id FROM communication_campaigns WHERE status IN ('scheduled','processing') AND (scheduled_at IS NULL OR scheduled_at<=?) ORDER BY id LIMIT ?");$s->execute([($this->clock)()->format('Y-m-d H:i:s'),max(1,min(100,$limit))]);$n=0;foreach($s->fetchAll(PDO::FETCH_COLUMN) as $id)$n+=$this->queueBatch((int)$id,100);return $n;}
    public function all():array{return $this->pdo->query("SELECT c.*, (SELECT COUNT(*) FROM communication_campaign_recipients r WHERE r.campaign_id=c.id) AS recipients FROM communication_campaigns c ORDER BY c.id DESC")->fetchAll(PDO::FETCH_ASSOC);}
    public function find(int $id):?array {$s=$this->pdo->prepare('SELECT * FROM communication_campaigns WHERE id=?');$s->execute([$id]);return $s->fetch(PDO::FETCH_ASSOC)?:null;}
    public function history(int $id):array {$concat=$this->pdo->getAttribute(PDO::ATTR_DRIVER_NAME)==='mysql'?'CONCAT(?,r.user_id)':'? || r.user_id';$s=$this->pdo->prepare('SELECT r.*,o.status AS outbox_status,o.sent_at,o.last_error_code FROM communication_campaign_recipients r LEFT JOIN communication_email_outbox o ON o.dedupe_key=('.$concat.') WHERE r.campaign_id=? ORDER BY r.user_id');$s->execute(['campaign:'.$id.':user:',$id]);return $s->fetchAll(PDO::FETCH_ASSOC);}
    private function eligible(array $campaign,int $limit):array {$sql="SELECT u.id,u.name,u.email FROM users u INNER JOIN communication_preferences p ON p.user_id=u.id AND p.category='marketing' AND p.email_enabled=1 AND p.marketing_opted_in_at IS NOT NULL WHERE u.status='active' AND u.id>?";$args=[(int)$campaign['recipient_cursor']];if($campaign['segment']==='plan'){$sql.=' AND u.plan_id=?';$args[]=(int)$campaign['plan_id'];}if($campaign['segment']==='new'){$sql.=' AND u.created_at>=?';$args[]=($this->clock)()->modify('-30 days')->format('Y-m-d H:i:s');}$sql.=' ORDER BY u.id LIMIT '.(int)$limit;$s=$this->pdo->prepare($sql);$s->execute($args);return $s->fetchAll(PDO::FETCH_ASSOC);}
    private function recipient(int $campaign,array $user):void {$mysql=$this->pdo->getAttribute(PDO::ATTR_DRIVER_NAME)==='mysql';$sql='INSERT INTO communication_campaign_recipients(campaign_id,user_id,recipient,status,created_at) VALUES(?,?,?,\'pending\',?)'.($mysql?' ON DUPLICATE KEY UPDATE recipient=VALUES(recipient)':' ON CONFLICT(campaign_id,user_id) DO NOTHING');$this->pdo->prepare($sql)->execute([$campaign,$user['id'],$user['email'],($this->clock)()->format('Y-m-d H:i:s')]);}
    private function campaign(int $id,bool $lock=false):array {$s=$this->pdo->prepare('SELECT * FROM communication_campaigns WHERE id=?'.($lock&&$this->pdo->getAttribute(PDO::ATTR_DRIVER_NAME)==='mysql'?' FOR UPDATE':''));$s->execute([$id]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!is_array($r))throw new InvalidArgumentException('Campanha não encontrada.');return $r;}
    private function template(int $id):array {$s=$this->pdo->prepare("SELECT * FROM communication_email_templates WHERE id=? AND event='marketing.campaign'");$s->execute([$id]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!is_array($r))throw new InvalidArgumentException('Template de marketing inválido.');return $r;}
    private function data(array $in):array {$name=trim((string)($in['name']??''));$title=trim((string)($in['title']??''));$body=trim((string)($in['body']??''));$template=(int)($in['template_id']??0);$segment=(string)($in['segment']??'active');$plan=$segment==='plan'?(int)($in['plan_id']??0):null;if($name===''||$title===''||$body===''||mb_strlen($name)>180||mb_strlen($title)>255||mb_strlen($body)>4000||$template<1||!in_array($segment,['active','plan','new'],true)||($segment==='plan'&&$plan<1))throw new InvalidArgumentException('Dados da campanha inválidos.');return compact('name','title','body','template','segment','plan')+['template_id'=>$template,'plan_id'=>$plan];}
    private function assertActor(int $actor):void {if($actor<1)throw new InvalidArgumentException('Administrador inválido.');}
}
