<?php declare(strict_types=1); $money=static fn($c):string=>($filters['currency']==='BRL'?'R$':$filters['currency']).' '.number_format(((int)$c)/100,2,',','.'); ob_start(); ?>
<section class="admin-page-head"><div><p class="admin-eyebrow">Dados financeiros</p><h2>Financeiro</h2><p>Recebimentos menos estornos confirmados. Créditos operacionais não são receita.</p></div></section>
<section class="admin-panel"><form method="get" action="/admin/financeiro" class="admin-form-grid">
<label>Ambiente<select name="environment"><option value="production"<?= $filters['environment']==='production'?' selected':'' ?>>Produção</option><option value="sandbox"<?= $filters['environment']==='sandbox'?' selected':'' ?>>Sandbox — não é receita real</option></select></label>
<label>Moeda<input name="currency" pattern="[A-Z]{3}" maxlength="3" value="<?= e($filters['currency']) ?>" required></label>
<label>Gateway<select name="gateway"><option value="">Todos</option><?php foreach(['stripe','pagarme'] as $v): ?><option value="<?= $v ?>"<?= $filters['gateway']===$v?' selected':'' ?>><?= $v ?></option><?php endforeach; ?></select></label>
<label>Status<select name="status"><option value="">Todos</option><?php foreach(['paid'=>'Pago','pending'=>'Pendente','failed'=>'Recusado','canceled'=>'Cancelado','refunded'=>'Estornado'] as $key=>$label): ?><option value="<?= $key ?>"<?= $filters['status']===$key?' selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></label>
<label>Usuário<input name="user" inputmode="numeric" value="<?= e($filters['user']) ?>"></label><label>Plano<input name="plan" inputmode="numeric" value="<?= e($filters['plan']) ?>"></label>
<label>De (UTC)<input type="date" name="from" value="<?= e($filters['from']) ?>"></label><label>Até (UTC)<input type="date" name="to" value="<?= e($filters['to']) ?>"></label><button class="admin-button">Filtrar</button></form></section>
<?php if($filters['environment']==='sandbox'): ?><section class="admin-panel"><strong>Ambiente de teste: estes valores não representam receita real.</strong></section><?php endif; ?>
<section class="admin-panel"><p><strong><?= (int)$totals['count'] ?></strong> registros · bruto <?= e($money($totals['gross_cents'])) ?> · líquido <?= e($money($totals['paid_cents'])) ?></p><p>Exibindo os 50 registros mais recentes. Os totais consideram todos os registros dos filtros.</p><div class="admin-table-wrap"><table><thead><tr><th>Usuário</th><th>Plano</th><th>Gateway</th><th>Status</th><th>Pago</th><th>Estornado</th><th>Líquido</th></tr></thead><tbody>
<?php foreach($records as $row): ?><tr><td><a href="/admin/usuarios/<?= (int)$row['user_id'] ?>"><?= e((string)$row['user_email']) ?></a></td><td><?= e((string)($row['plan_name']??$row['plan_id'])) ?></td><td><?= e((string)$row['provider']) ?></td><td><?= e((string)$row['status']) ?></td><td><?= e($money($row['paid_amount_cents'])) ?></td><td><?= e($money($row['refunded_amount_cents'])) ?></td><td><?= e($money($row['net_amount_cents'])) ?></td></tr><?php endforeach; ?>
<?php if($records===[]): ?><tr><td colspan="7">Nenhum pagamento para estes filtros.</td></tr><?php endif; ?></tbody></table></div></section>
<?php if(isset($summary)): ?><section class="admin-panel"><h2>Assinaturas e mês atual — produção / BRL</h2><p><?= (int)$summary['subscriptions_total'] ?> assinaturas · <?= (int)$summary['subscriptions_active'] ?> ativas · <?= (int)$summary['subscriptions_canceled'] ?> canceladas.</p><p>Receita líquida do mês (UTC): BRL <?= number_format($summary['net_month_cents']/100,2,',','.') ?>. Estes indicadores gerais não usam os filtros acima.</p></section><?php endif; ?>
<?php $content=(string)ob_get_clean(); require __DIR__.'/../layouts/admin.php';
