<?php
declare(strict_types=1);
namespace Tests\Support;
use PDO;
final class ThumbnailTestDatabase
{
 public static function create(): PDO {
  $p=new PDO('sqlite::memory:',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
  $p->exec("CREATE TABLE projects(id INTEGER PRIMARY KEY,user_id INTEGER,status TEXT); CREATE TABLE ai_analyses(id INTEGER PRIMARY KEY,project_id INTEGER); CREATE TABLE project_sources(id INTEGER PRIMARY KEY,project_id INTEGER,status TEXT,object_key TEXT,mime_type TEXT); CREATE TABLE clips(id INTEGER PRIMARY KEY,project_id INTEGER,ai_analysis_id INTEGER,title TEXT,status TEXT,render_revision INTEGER,render_start_time REAL,render_end_time REAL,output_file TEXT,output_size_bytes INTEGER,thumbnail TEXT); INSERT INTO projects VALUES(1,7,'completed'),(2,8,'completed'); INSERT INTO ai_analyses VALUES(1,1),(2,2); INSERT INTO project_sources VALUES(1,1,'ready','sources/test.mp4','video/mp4'),(2,2,'ready','sources/other.mp4','video/mp4'); INSERT INTO clips VALUES(1,1,1,'Clipe','completed',1,0,10,'processed/a.mp4',300,'thumbnails/original.jpg'),(2,2,2,'Outro','completed',1,0,10,'processed/b.mp4',300,'thumbnails/other.jpg');");
  $p->exec("CREATE TABLE clip_thumbnail_sets(id INTEGER PRIMARY KEY AUTOINCREMENT,clip_id INTEGER,user_id INTEGER,render_revision INTEGER,request_key TEXT,status TEXT,error_code TEXT,candidate_count INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(clip_id,render_revision),UNIQUE(user_id,request_key)); CREATE TABLE clip_thumbnails(id INTEGER PRIMARY KEY AUTOINCREMENT,set_id INTEGER,clip_id INTEGER,user_id INTEGER,render_revision INTEGER,kind TEXT,candidate_index INTEGER,offset_seconds REAL,base_thumbnail_id INTEGER,request_key TEXT,options_json TEXT,status TEXT,error_code TEXT,object_key TEXT UNIQUE,size_bytes INTEGER,mime_type TEXT,width INTEGER,height INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(set_id,candidate_index),UNIQUE(user_id,request_key)); CREATE TABLE publication_preparations(id INTEGER PRIMARY KEY AUTOINCREMENT,clip_id INTEGER,user_id INTEGER,render_revision INTEGER,thumbnail_id INTEGER,platform TEXT,metadata_json TEXT,status TEXT,version INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE publication_events(id INTEGER PRIMARY KEY AUTOINCREMENT,publication_id INTEGER,user_id INTEGER,version INTEGER,status TEXT,snapshot_json TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(publication_id,version));"); return $p;
 }
}
