CREATE TABLE IF NOT EXISTS ai_analyses (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT UNSIGNED NOT NULL,
    prompt_version VARCHAR(32) NOT NULL,
    model VARCHAR(100) NOT NULL,
    status ENUM('queued','uploading','waiting_file','generating','validating','completed','failed') NOT NULL DEFAULT 'queued',
    gemini_file_name VARCHAR(128) NULL,
    gemini_file_uri VARCHAR(1024) NULL,
    gemini_file_mime VARCHAR(100) NULL,
    gemini_file_state ENUM('PROCESSING','ACTIVE','FAILED') NULL,
    video_summary TEXT NULL,
    validated_response_json JSON NULL,
    validation_attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
    provider_request_id VARCHAR(128) NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(255) NULL,
    completed_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_ai_analysis_project_prompt (project_id, prompt_version),
    KEY idx_ai_analysis_status_created (status, created_at),
    CONSTRAINT fk_ai_analysis_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS credit_reservations (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    project_id BIGINT UNSIGNED NOT NULL,
    operation VARCHAR(32) NOT NULL DEFAULT 'ai_analysis',
    units INT UNSIGNED NOT NULL,
    status ENUM('reserved','consumed','refunded') NOT NULL DEFAULT 'reserved',
    idempotency_key CHAR(64) NOT NULL,
    credit_transaction_id BIGINT UNSIGNED NULL,
    refund_transaction_id BIGINT UNSIGNED NULL,
    consumed_at DATETIME NULL,
    refunded_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_credit_reservation_user_key (user_id, idempotency_key),
    KEY idx_credit_reservation_project_status (project_id, status),
    CONSTRAINT fk_credit_reservation_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_credit_reservation_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_credit_reservation_debit FOREIGN KEY (credit_transaction_id) REFERENCES credit_transactions (id),
    CONSTRAINT fk_credit_reservation_refund FOREIGN KEY (refund_transaction_id) REFERENCES credit_transactions (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS clips (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT UNSIGNED NOT NULL,
    ai_analysis_id BIGINT UNSIGNED NOT NULL,
    suggestion_index TINYINT UNSIGNED NOT NULL,
    title VARCHAR(180) NOT NULL,
    start_time DECIMAL(10,3) UNSIGNED NOT NULL,
    end_time DECIMAL(10,3) UNSIGNED NOT NULL,
    duration_seconds DECIMAL(10,3) UNSIGNED NOT NULL,
    viral_score TINYINT UNSIGNED NOT NULL,
    hook VARCHAR(500) NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    category VARCHAR(32) NOT NULL,
    status ENUM('suggested','approved','queued','rendering','completed','failed') NOT NULL DEFAULT 'suggested',
    output_file VARCHAR(255) NULL,
    thumbnail VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_clips_analysis_index (ai_analysis_id, suggestion_index),
    KEY idx_clips_project_status_score (project_id, status, viral_score),
    CONSTRAINT fk_clips_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_clips_analysis FOREIGN KEY (ai_analysis_id) REFERENCES ai_analyses (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
