<?php declare(strict_types=1);use App\Core\Csrf;ob_start(); ?>
<link rel="stylesheet" href="/assets/css/email-studio.css">
<div class="email-studio">
<section class="admin-page-head email-studio-head"><div><p class="admin-eyebrow">Comunicação / Entrega de e-mails</p><h2>Uma conexão para<br>manter a conversa.</h2><p>Configure o remetente e conecte seu serviço de e-mail. Depois, envie um teste para conferir a experiência na caixa de entrada.</p></div><a class="email-text-link" href="/admin/emails">Voltar aos modelos <span aria-hidden="true">→</span></a></section>
<?php if($message): ?><p class="admin-flash" role="status"><?= e($message) ?></p><?php endif; ?>
<div class="email-settings-grid">
<section class="admin-panel email-settings-card"><p class="admin-eyebrow">Identidade e conexão</p><h2>Quem assina suas mensagens.</h2><p>Use os dados fornecidos pelo seu serviço de e-mail. As credenciais salvas ficam cifradas.</p>
<form class="email-settings-form" method="post" action="/admin/email-configuracao" data-platform-form><input type="hidden" name="_token" value="<?= e(Csrf::token()) ?>">
<fieldset><legend>01 / Remetente</legend><label>Nome do remetente<input name="from_name" maxlength="120" required value="<?= e((string)($settings['from_name']??'ClipLab')) ?>"><small>Como sua marca aparece na caixa de entrada.</small></label><label>E-mail remetente<input type="email" name="from_address" required placeholder="equipe@seudominio.com" value="<?= e((string)($settings['from_address']??'')) ?>"></label></fieldset>
<fieldset><legend>02 / Servidor de e-mail</legend><label>Servidor SMTP<input name="smtp_host" required placeholder="smtp.seuprovedor.com" value="<?= e((string)($settings['smtp_host']??'')) ?>"></label><label>Porta<input type="number" min="1" max="65535" name="smtp_port" required value="<?= e((string)($settings['smtp_port']??587)) ?>"></label><label>Criptografia<select name="smtp_encryption"><option value="tls" <?= ($settings['smtp_encryption']??'tls')==='tls'?'selected':'' ?>>STARTTLS</option><option value="ssl" <?= ($settings['smtp_encryption']??'')==='ssl'?'selected':'' ?>>TLS implícito (SSL)</option></select></label><label>Tempo limite (segundos)<input name="smtp_timeout" type="number" min="1" max="60" value="<?= e((string)($settings['smtp_timeout']??10)) ?>"></label></fieldset>
<fieldset><legend>03 / Autenticação</legend><label>Usuário SMTP<input name="smtp_username" autocomplete="off" value="<?= e((string)($settings['smtp_username']??'')) ?>"></label><label>Senha SMTP<input type="password" name="smtp_password" autocomplete="new-password"><small><?= !empty($settings['has_password'])?'Deixe vazia para manter a senha salva.':'Informe a senha quando houver usuário SMTP.' ?></small></label></fieldset>
<button class="admin-button" type="submit">Salvar configuração <span aria-hidden="true">↗</span></button></form></section>
<aside class="admin-panel email-settings-card"><p class="admin-eyebrow">Conferir entrega</p><h2>Daqui até sua caixa de entrada.</h2><div class="email-delivery-state"><strong><?= !empty($settings['configured'])?'Configuração disponível':'SMTP ainda não configurado' ?></strong><p>Origem: <?= ($settings['source']??'')==='database'?'salva neste painel':'configuração do ambiente' ?>.</p><?php if(!empty($settings['last_tested_at'])): ?><p>Último teste: <?= e($settings['last_tested_at']) ?>.<br><?= ($settings['last_test_status']??'')==='success'?'Aceito pelo servidor SMTP.':'O último teste falhou.' ?></p><?php else: ?><p>Nenhum teste registrado neste painel.</p><?php endif; ?></div><p>O teste será enviado apenas para <strong><?= e($admin['email']) ?></strong>.</p><form method="post" action="/admin/email-configuracao/testar"><input type="hidden" name="_token" value="<?= e(Csrf::token()) ?>"><button class="admin-button" type="submit">Enviar teste real para meu e-mail</button></form><p class="email-delivery-note">Até três testes a cada 15 minutos. Após o envio, confira a caixa de entrada e o spam. O aceite do servidor não comprova a entrega.</p></aside>
</div></div>
<?php $content=(string)ob_get_clean();require __DIR__.'/../layouts/admin.php'; ?>
