<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Communications\CampaignService; use App\Communications\CampaignUnsubscribeService; use App\Core\{Request,Response,Session,View}; use DateTimeImmutable; use PDO; use Throwable;
final class CampaignController {
 public function __construct(private View $view,private CampaignService $campaigns,private CampaignUnsubscribeService $unsubscribe,private PDO $pdo){}
 private function actor():array{$s=$this->pdo->prepare("SELECT id,name,email FROM users WHERE id=? AND role='admin' AND status='active'");$s->execute([(int)Session::get('user_id',0)]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!is_array($r))throw new \DomainException('Administrador inválido.');return $r;}
 public function index(Request $r):Response{return $this->admin('campaigns.index',['campaigns'=>$this->campaigns->all()]);}
 public function form(Request $r,array $p=[]):Response{$campaign=isset($p['id'])?$this->campaigns->find((int)$p['id']):null;if(isset($p['id'])&&!is_array($campaign))return Response::text('Não encontrado.',404);return $this->admin('campaigns.form',['campaign'=>$campaign,'templates'=>$this->templates()]);}
 public function create(Request $r):Response{try{$id=$this->campaigns->create((int)$this->actor()['id'],$this->input($r));Session::flash('campaign_flash',['type'=>'success','message'=>'Rascunho criado.']);return Response::redirect('/admin/campanhas/'.$id.'/editar');}catch(Throwable){Session::flash('campaign_flash',['type'=>'error','message'=>'Não foi possível salvar o rascunho.']);return Response::redirect('/admin/campanhas/nova');}}
 public function update(Request $r,array $p):Response{$id=(int)($p['id']??0);try{$this->campaigns->update((int)$this->actor()['id'],$id,$this->input($r));Session::flash('campaign_flash',['type'=>'success','message'=>'Rascunho atualizado.']);}catch(Throwable){Session::flash('campaign_flash',['type'=>'error','message'=>'Não foi possível alterar esta campanha.']);}return Response::redirect('/admin/campanhas/'.$id.'/editar');}
 public function schedule(Request $r,array $p):Response{$id=(int)($p['id']??0);try{$at=new DateTimeImmutable((string)$r->input('scheduled_at','now'));$this->campaigns->schedule((int)$this->actor()['id'],$id,$at);Session::flash('campaign_flash',['type'=>'success','message'=>'Campanha agendada para enfileiramento.']);}catch(Throwable){Session::flash('campaign_flash',['type'=>'error','message'=>'Não foi possível agendar.']);}return Response::redirect('/admin/campanhas');}
 public function cancel(Request $r,array $p):Response{$id=(int)($p['id']??0);try{$this->campaigns->cancel((int)$this->actor()['id'],$id);Session::flash('campaign_flash',['type'=>'success','message'=>'Campanha cancelada; envios pendentes foram removidos.']);}catch(Throwable){Session::flash('campaign_flash',['type'=>'error','message'=>'Não foi possível cancelar.']);}return Response::redirect('/admin/campanhas');}
 public function history(Request $r,array $p):Response{$id=(int)($p['id']??0);if($this->campaigns->find($id)===null)return Response::text('Não encontrado.',404);return $this->admin('campaigns.history',['campaign'=>$this->campaigns->find($id),'rows'=>$this->campaigns->history($id)]);}
 public function unsubscribeForm(Request $r):Response{try{$this->unsubscribe->resolve((string)$r->query('token',''));return $this->view->render('campaigns.unsubscribe',['token'=>(string)$r->query('token',''),'message'=>Session::pull('campaign_unsubscribe_message')]);}catch(Throwable){return Response::text('Link de cancelamento inválido ou expirado.',422);}}
 public function unsubscribe(Request $r):Response{try{$this->unsubscribe->unsubscribe((string)$r->input('token',''));Session::flash('campaign_unsubscribe_message','Seu e-mail foi removido das campanhas de marketing.');}catch(Throwable){Session::flash('campaign_unsubscribe_message','Não foi possível confirmar este link.');}return Response::redirect('/cancelar-inscricao?token='.rawurlencode((string)$r->input('token','')));}
 private function admin(string $view,array $data):Response{return $this->view->render($view,$data+['title'=>'Campanhas','admin'=>$this->actor(),'flash'=>Session::pull('campaign_flash')]);}
 private function templates():array{return $this->pdo->query("SELECT id,subject_template,version,is_active FROM communication_email_templates WHERE event='marketing.campaign' ORDER BY version DESC")->fetchAll(PDO::FETCH_ASSOC);}
 private function input(Request $r):array{return ['name'=>$r->input('name',''),'template_id'=>$r->input('template_id',0),'title'=>$r->input('title',''),'body'=>$r->input('body',''),'segment'=>$r->input('segment','active'),'plan_id'=>$r->input('plan_id',null)];}
}
