<?php
declare(strict_types=1);
$title = 'Seu próximo corte já está gravado';
$publicPlans = $publicPlans ?? [];
$publicTestimonials = $publicTestimonials ?? [];
$startUrl = !empty($_SESSION['user_id']) ? '/projetos/novo' : '/cadastro';
ob_start();
?>
<a class="skip-link" href="#conteudo">Pular para o conteúdo</a>
<header class="site-header" data-header><nav class="container nav-shell" aria-label="Navegação principal">
<a class="brand" href="/" aria-label="ClipLab, início"><?php $logoId = 'nav-logo'; require __DIR__ . '/components/logo.php'; ?></a>
<button class="nav-toggle" type="button" aria-expanded="false" aria-controls="menu-principal" data-nav-toggle><span class="visually-hidden">Abrir menu</span><i data-lucide="menu" aria-hidden="true"></i></button>
<div class="nav-links" id="menu-principal" data-nav-menu><a href="#como-funciona">Início</a><a href="#recursos">Funcionalidades</a><a href="#recursos">Campeonatos</a><?php if ($publicPlans !== []): ?><a href="#planos">Preços</a><?php endif; ?><a href="#relatos">Blog</a><a class="nav-login" href="/login">Entrar</a><a class="button button-small" href="<?= e($startUrl) ?>">Começar a criar <i data-lucide="arrow-up-right" aria-hidden="true"></i></a></div>
</nav></header>
<main id="conteudo">
<section class="landing-hero" aria-labelledby="hero-title"><div class="container landing-hero-grid">
<div class="landing-hero-copy"><p class="landing-kicker"><span class="landing-status-dot" aria-hidden="true"></span> DO VÍDEO INTEIRO AO TRECHO CERTO</p><h1 id="hero-title"><span class="landing-hero-line">Transforme</span> <span class="landing-hero-line">seus vídeos</span> <span class="landing-hero-result">em <em>resultados.</em></span></h1><p class="landing-lede">A ClipLab usa inteligência artificial para encontrar os melhores momentos, criar cortes virais e te ajudar a publicar em todas as plataformas.</p><div class="landing-actions"><a class="button" href="<?= e($startUrl) ?>">Começar grátis <i data-lucide="arrow-up-right" aria-hidden="true"></i></a><a class="landing-demo-link" href="#demonstracao">Conhecer o estúdio <i data-lucide="arrow-down" aria-hidden="true"></i></a></div><p class="landing-hero-note">3 dias grátis • Sem cartão de crédito • Cancele quando quiser</p>
<div class="studio-chrome"><span class="studio-brand"><i data-lucide="clapperboard" aria-hidden="true"></i> ClipLab <span>/ estúdio</span></span><span class="studio-demo-label">Demonstração ilustrativa</span></div>
<div class="studio-project"><div><span class="studio-overline">PROJETO DE EXEMPLO</span><strong>Ideias que ficam</strong></div><span class="studio-project-type">CONVERSA · 12:40</span></div>
<div class="studio-stage" data-demo-stage="1"><div class="studio-stage-heading"><span>01 / Sua matéria-prima</span><i data-lucide="film" aria-hidden="true"></i></div><div class="studio-source-screen" aria-label="Representação gráfica de um vídeo de exemplo, sem mídia real"><span class="studio-screen-top">VÍDEO ORIGINAL <span>16:9</span></span><div class="studio-screen-title">Uma boa conversa.<br><strong>Muitos começos.</strong></div><span class="studio-caption">“Toda ideia começa com uma pergunta.”</span><div class="studio-video-bar"><i data-lucide="play" aria-hidden="true"></i><span class="studio-track"><span></span></span><span>02:18 / 12:40</span></div></div><div class="studio-source-meta"><span><i data-lucide="file-video" aria-hidden="true"></i> conversa-criativa.mp4</span><span>Arquivo de exemplo</span></div><p class="studio-stage-note">No seu projeto, envie um vídeo ou use uma URL HTTPS direta.</p></div>
<div class="studio-stage" data-demo-stage="2" hidden><div class="studio-stage-heading"><span>02 / Uma ideia ganha destaque</span><i data-lucide="sparkles" aria-hidden="true"></i></div><div class="studio-suggestion"><span class="studio-suggestion-number">01</span><div><span class="studio-overline">SUGESTÃO ILUSTRATIVA</span><h3>O começo de uma boa ideia</h3><p>02:18 → 03:02 <span>44 segundos</span></p></div><i data-lucide="scissors" aria-hidden="true"></i></div><div class="studio-transcript"><span class="studio-overline">TRECHO DO EXEMPLO</span><p><span>Às vezes a gente espera a ideia perfeita.</span> <mark>Mas toda ideia começa com uma pergunta. O primeiro passo é dar espaço para ela.</mark> <span>Depois, vem o trabalho de encontrar a forma.</span></p></div><div class="studio-timeline" aria-label="Linha do tempo ilustrativa com um trecho selecionado"><div class="studio-wave" aria-hidden="true"><?php for ($i = 0; $i < 46; $i++): ?><span></span><?php endfor; ?></div><span class="studio-selection">TRECHO SELECIONADO</span></div><p class="studio-stage-note">A IA sugere. Você revisa o contexto e decide o que fica.</p></div>
<div class="studio-stage" data-demo-stage="3" hidden><div class="studio-stage-heading"><span>03 / Seu corte, do seu jeito</span><i data-lucide="sliders-horizontal" aria-hidden="true"></i></div><div class="studio-export"><div class="studio-portrait"><span>CORTE 01</span><p>Toda ideia<br>começa com<br><mark>uma pergunta.</mark></p><span>9:16 · EXEMPLO</span></div><div class="studio-export-details"><span class="studio-overline">AJUSTES DO EXEMPLO</span><dl><div><dt>Proporção</dt><dd>Vertical · 9:16</dd></div><div><dt>Legendas</dt><dd>Revisadas por você</dd></div><div><dt>Duração</dt><dd>00:44</dd></div><div><dt>Saída</dt><dd>Arquivo de vídeo</dd></div></dl><span class="studio-export-badge"><i data-lucide="download" aria-hidden="true"></i> Revise antes de exportar</span></div></div><p class="studio-stage-note">Ajuste no editor, exporte e publique nos seus canais.</p></div>
<div class="studio-demo-controls"><div class="studio-demo-steps" aria-label="Etapas da demonstração"><button type="button" data-demo-select="1" aria-current="step" aria-label="Ver etapa 1: origem">01 <span>Origem</span></button><button type="button" data-demo-select="2" aria-label="Ver etapa 2: sugestões">02 <span>Sugestões</span></button><button type="button" data-demo-select="3" aria-label="Ver etapa 3: exportação">03 <span>Exportação</span></button></div><div class="studio-demo-arrows"><button type="button" data-demo-prev aria-label="Etapa anterior" disabled><i data-lucide="arrow-left" aria-hidden="true"></i></button><button type="button" data-demo-next aria-label="Próxima etapa"><i data-lucide="arrow-right" aria-hidden="true"></i></button></div></div><span class="visually-hidden" data-demo-status aria-live="polite">Etapa 1 de 3: origem.</span><noscript><p class="studio-stage-note">Prévia estática. Ative JavaScript para explorar as três etapas.</p></noscript>
</div></div></section>
<div class="container landing-audience"><span>FEITO PARA O SEU CONTEÚDO</span><p><i data-lucide="scissors" aria-hidden="true"></i>Cortes automáticos</p><span class="landing-audience-plus" aria-hidden="true">+</span><p><i data-lucide="captions" aria-hidden="true"></i>Legendas dinâmicas</p><span class="landing-audience-plus" aria-hidden="true">+</span><p><i data-lucide="smartphone" aria-hidden="true"></i>Formatos para todas as plataformas</p><span class="landing-audience-plus" aria-hidden="true">+</span><p><i data-lucide="cloud-upload" aria-hidden="true"></i>Publicação automática</p><span class="landing-audience-plus" aria-hidden="true">+</span><p><i data-lucide="bar-chart-3" aria-hidden="true"></i>Estatísticas e desempenho</p></div>
<section class="landing-section landing-manifesto"><div class="container landing-manifesto-grid"><p class="landing-kicker">O MATERIAL JÁ É SEU.<br>O PRÓXIMO PASSO TAMBÉM.</p><div><h2>Gravar deu trabalho.<br><span>Reaproveitar pode ser mais simples.</span></h2><p>Um vídeo longo pode guardar várias boas entradas para a mesma história. O ClipLab ajuda a localizar esses trechos e reúne revisão, edição e exportação em um só fluxo.</p></div></div></section>
<section id="como-funciona" class="landing-section" aria-labelledby="steps-title"><div class="container"><div class="landing-section-heading"><div><p class="landing-kicker">DA ORIGEM À EXPORTAÇÃO</p><h2 id="steps-title">Três etapas.<br>Seu olhar em todas elas.</h2></div><p>A tecnologia encurta o caminho.<br>A decisão criativa continua com você.</p></div><ol class="landing-steps"><li><span class="landing-step-number">01</span><i data-lucide="upload" aria-hidden="true"></i><h3>Traga o vídeo inteiro.</h3><p>Envie seu arquivo ou informe uma URL HTTPS direta de um vídeo que você tem autorização para usar.</p><span class="landing-step-foot">UM PONTO DE PARTIDA</span></li><li><span class="landing-step-number">02</span><i data-lucide="scan-search" aria-hidden="true"></i><h3>Encontre o que vale um corte.</h3><p>Analise o material com IA e confira as sugestões. Reveja cada trecho para preservar a intenção da sua mensagem.</p><span class="landing-step-foot">SUGESTÃO + SEU CRITÉRIO</span></li><li><span class="landing-step-number">03</span><i data-lucide="download" aria-hidden="true"></i><h3>Dê forma. Exporte.</h3><p>Ajuste duração, enquadramento e legendas no editor. Baixe o resultado para publicar onde fizer sentido.</p><span class="landing-step-foot">SEU PRÓXIMO PASSO</span></li></ol></div></section>
<section id="recursos" class="landing-section landing-workbench" aria-labelledby="features-title"><div class="container"><div class="landing-section-heading"><div><p class="landing-kicker">DENTRO DO ESTÚDIO</p><h2 id="features-title">O detalhe faz<br><em>o seu corte.</em></h2></div><p>Ajuste o ritmo, cuide do texto e escolha como a imagem aparece. O resultado passa pelo seu olhar.</p></div>
<?php if (is_file(dirname(__DIR__, 2) . '/public/assets/images/editor-preview.png')): ?><figure class="landing-product-shot"><a href="<?= e($startUrl) ?>"><img src="/assets/images/editor-preview.png" width="1152" height="900" loading="lazy" alt="Editor real do ClipLab com prévia de vídeo, controles de legendas e ajustes do clipe, preenchido com dados de demonstração"></a><figcaption><span>Editor do ClipLab · dados de demonstração</span><a href="<?= e($startUrl) ?>">Criar no meu estúdio <i data-lucide="arrow-up-right" aria-hidden="true"></i></a><small class="landing-image-credit">Cena de <a href="https://durian.blender.org/about/" target="_blank" rel="noopener noreferrer">Sintel · © Blender Foundation</a> · <a href="https://creativecommons.org/licenses/by/3.0/" target="_blank" rel="noopener noreferrer">CC BY 3.0</a></small></figcaption></figure><?php endif; ?>
<div class="landing-editor-notes"><article><span>01 / CORTE</span><h3>Entre e saia no momento certo.</h3><p>Ajuste o início e o fim do trecho. Preserve a pausa, a resposta e o contexto que importam.</p></article><article><span>02 / LEGENDAS</span><h3>Suas palavras, bem apresentadas.</h3><p>Revise as legendas e personalize sua aparência. O texto também faz parte da sua edição.</p></article><article><span>03 / ENQUADRAMENTO</span><h3>Escolha o espaço da história.</h3><p>Prepare versões verticais, quadradas ou horizontais. Confira a prévia antes de exportar.</p></article></div></div></section>
<section class="landing-section landing-benefits"><div class="container"><p class="landing-kicker">MAIS POSSIBILIDADES PARA O MESMO MATERIAL</p><div class="landing-benefits-grid"><h2>Não precisa começar<br>do zero toda vez.</h2><div><article><i data-lucide="layers" aria-hidden="true"></i><div><h3>Um original. Novas versões.</h3><p>Explore diferentes trechos sem perder a referência do projeto.</p></div></article><article><i data-lucide="folder-open" aria-hidden="true"></i><div><h3>Um lugar para continuar.</h3><p>Volte aos projetos e clipes para retomar o trabalho.</p></div></article><article><i data-lucide="check-check" aria-hidden="true"></i><div><h3>O resultado passa por você.</h3><p>Revise as sugestões da IA e faça os ajustes antes de baixar.</p></div></article></div></div></div></section>
<?php if (is_file(__DIR__ . '/components/marketing-plans.php')) { require __DIR__ . '/components/marketing-plans.php'; } ?>
<?php if (is_file(__DIR__ . '/components/marketing-proof.php')) { require __DIR__ . '/components/marketing-proof.php'; } ?>
<section id="duvidas" class="landing-section" aria-labelledby="faq-title"><div class="container landing-faq-grid"><div><p class="landing-kicker">ANTES DO PRIMEIRO CORTE</p><h2 id="faq-title">Bom saber.</h2><p>As respostas para começar com clareza.</p></div><div class="landing-faq"><details><summary>Que vídeos posso usar?<i data-lucide="plus" aria-hidden="true"></i></summary><p>Envie um arquivo ou uma URL HTTPS direta para um vídeo. Use apenas material seu ou que você tenha autorização para editar. A importação de vídeos públicos do YouTube depende de estar habilitada e da disponibilidade da fonte; nem todo link poderá ser importado.</p></details><details><summary>A IA faz tudo sozinha?<i data-lucide="plus" aria-hidden="true"></i></summary><p>A IA ajuda a analisar o material e sugerir trechos. Você confere as sugestões, revisa o conteúdo e usa o editor para ajustar o resultado. A análise pode levar tempo e depende da duração do vídeo e dos limites do plano.</p></details><details><summary>Posso editar os cortes sugeridos?<i data-lucide="plus" aria-hidden="true"></i></summary><p>Sim. No editor, você pode ajustar o intervalo do corte, o enquadramento e as legendas antes de exportar. Confira a prévia para decidir como quer apresentar cada trecho.</p></details><details><summary>O ClipLab publica nas minhas redes?<i data-lucide="plus" aria-hidden="true"></i></summary><p>A exportação gera um arquivo para baixar. Você faz a publicação nos seus canais; o ClipLab não conecta nem publica automaticamente em redes sociais.</p></details><details><summary>Como funcionam os planos e limites?<i data-lucide="plus" aria-hidden="true"></i></summary><p>O catálogo mostra os créditos, minutos e limites de cada plano. A contratação ou alteração é confirmada pela administração, sem cobrança online automática. Confira os detalhes na sua conta antes de iniciar um projeto.</p></details></div></div></section>
<section class="landing-final"><div class="container"><p class="landing-kicker">VOLTE AO QUE VOCÊ JÁ GRAVOU.</p><h2>Tem mais história<br><em>nesse vídeo.</em></h2><a class="button" href="<?= e($startUrl) ?>">Encontrar meu próximo corte <i data-lucide="arrow-up-right" aria-hidden="true"></i></a><p>Traga o material. O próximo passo é seu.</p></div><span class="landing-final-mark" aria-hidden="true">[ / ]</span></section>
</main>
<footer class="site-footer"><div class="container footer-shell"><a class="brand" href="/" aria-label="ClipLab, início"><?php $logoId = 'footer-logo'; require __DIR__ . '/components/logo.php'; ?></a><p>Novos cortes. A sua história.</p><div><a href="/privacidade">Privacidade</a><a href="/termos">Termos</a><a href="/login">Entrar</a></div><small>© <?= date('Y') ?> ClipLab.</small></div></footer>
<?php
$content = (string) ob_get_clean();
require __DIR__ . '/layouts/marketing.php';
