<?php
declare(strict_types=1);
namespace App\Repositories;
use PDO;
use App\Media\Thumbnails\PublicationVersionConflict;
final class PublicationPreparationRepository
{
 public function __construct(private PDO $pdo) {}
 public function findOwned(int $id,int $userId): ?array { $q=$this->pdo->prepare('SELECT pp.* FROM publication_preparations pp JOIN clips c ON c.id=pp.clip_id JOIN projects p ON p.id=c.project_id AND p.user_id=pp.user_id WHERE pp.id=? AND pp.user_id=?');$q->execute([$id,$userId]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r)return null;$r['metadata']=json_decode($r['metadata_json'],true,512,JSON_THROW_ON_ERROR);unset($r['metadata_json']);return $r; }
 public function forClip(int $clipId,int $userId): array { $q=$this->pdo->prepare('SELECT pp.id FROM publication_preparations pp JOIN clips c ON c.id=pp.clip_id JOIN projects p ON p.id=c.project_id AND p.user_id=pp.user_id WHERE pp.clip_id=? AND pp.user_id=? ORDER BY pp.id DESC LIMIT 100');$q->execute([$clipId,$userId]);return array_map(fn($id)=>$this->findOwned((int)$id,$userId),$q->fetchAll(PDO::FETCH_COLUMN)); }
 public function persist(int $id,int $userId,int $expected,array $v): int { $json=json_encode($v['metadata'],JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE);if($id===0){$q=$this->pdo->prepare('INSERT INTO publication_preparations(clip_id,user_id,render_revision,thumbnail_id,platform,metadata_json,status,version) VALUES(?,?,?,?,?,?,?,1)');$q->execute([$v['clip_id'],$userId,$v['render_revision'],$v['thumbnail_id'],$v['metadata']['platform'],$json,$v['status']]);$id=(int)$this->pdo->lastInsertId();}else{$q=$this->pdo->prepare('UPDATE publication_preparations SET thumbnail_id=?,platform=?,metadata_json=?,status=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=? AND version=?');$q->execute([$v['thumbnail_id'],$v['metadata']['platform'],$json,$v['status'],$id,$userId,$expected]);if($q->rowCount()!==1)throw new PublicationVersionConflict('Esta preparação foi alterada. Atualize a página e revise antes de salvar.');}$row=$this->findOwned($id,$userId);$snapshot=array_intersect_key($row,array_flip(['clip_id','render_revision','thumbnail_id','metadata','status','version']));$q=$this->pdo->prepare('INSERT INTO publication_events(publication_id,user_id,version,status,snapshot_json) VALUES(?,?,?,?,?)');$q->execute([$id,$userId,$row['version'],$row['status'],json_encode($snapshot,JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE)]);return $id; }
 public function history(int $id,int $userId): array { if(!$this->findOwned($id,$userId))return [];$q=$this->pdo->prepare('SELECT version,status,snapshot_json,created_at FROM publication_events WHERE publication_id=? AND user_id=? ORDER BY version DESC');$q->execute([$id,$userId]);return $q->fetchAll(PDO::FETCH_ASSOC); }
}
