<?php
declare(strict_types=1);
namespace App\Repositories;
use PDO;
final class ThumbnailRepository
{
 public function __construct(private PDO $pdo) {}
 public function sourceOwned(int $clipId,int $userId,bool $lock=false): ?array {
  $q=$this->pdo->prepare("SELECT c.*,p.user_id,s.object_key AS source_object_key,s.id AS source_id FROM clips c JOIN projects p ON p.id=c.project_id JOIN project_sources s ON s.project_id=p.id WHERE c.id=? AND p.user_id=? AND c.status='completed' AND p.status <> 'archived' AND c.output_file IS NOT NULL AND c.output_size_bytes>0 AND s.status='ready' AND s.mime_type='video/mp4' AND s.object_key IS NOT NULL AND c.ai_analysis_id=(SELECT MAX(a.id) FROM ai_analyses a WHERE a.project_id=p.id) LIMIT 1".($lock&&$this->pdo->getAttribute(PDO::ATTR_DRIVER_NAME)==='mysql'?' FOR UPDATE':'')); $q->execute([$clipId,$userId]); return $q->fetch(PDO::FETCH_ASSOC)?:null;
 }
 public function findOwned(int $id,int $userId): ?array { $q=$this->pdo->prepare('SELECT * FROM clip_thumbnails WHERE id=? AND user_id=?');$q->execute([$id,$userId]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r)return null; $c=$this->sourceOwned((int)$r['clip_id'],$userId);return $c&&(int)$c['render_revision']===(int)$r['render_revision']?$r:null; }
 public function forClip(int $clipId,int $userId): array { $c=$this->sourceOwned($clipId,$userId); if(!$c)return []; $q=$this->pdo->prepare('SELECT * FROM clip_thumbnails WHERE clip_id=? AND user_id=? AND render_revision=? ORDER BY id DESC LIMIT 100');$q->execute([$clipId,$userId,$c['render_revision']]);return $q->fetchAll(PDO::FETCH_ASSOC); }
 public function setOwned(int $clipId,int $userId): ?array { $c=$this->sourceOwned($clipId,$userId);if(!$c)return null; $q=$this->pdo->prepare('SELECT * FROM clip_thumbnail_sets WHERE clip_id=? AND user_id=? AND render_revision=?');$q->execute([$clipId,$userId,$c['render_revision']]);return $q->fetch(PDO::FETCH_ASSOC)?:null; }
 public function requestOwned(string $key,int $userId,string $kind): ?array { $table=$kind==='set'?'clip_thumbnail_sets':'clip_thumbnails';$q=$this->pdo->prepare("SELECT * FROM $table WHERE request_key=? AND user_id=?");$q->execute([$key,$userId]);return $q->fetch(PDO::FETCH_ASSOC)?:null; }
 public function createSet(array $c,string $key): int { $q=$this->pdo->prepare("INSERT INTO clip_thumbnail_sets(clip_id,user_id,render_revision,request_key,status) VALUES(?,?,?,?,'pending')");$q->execute([$c['id'],$c['user_id'],$c['render_revision'],$key]);return (int)$this->pdo->lastInsertId(); }
 public function createDesign(array $c,string $key,float $offset,?int $base,array $options): int { $q=$this->pdo->prepare("INSERT INTO clip_thumbnails(clip_id,user_id,render_revision,kind,offset_seconds,base_thumbnail_id,request_key,options_json,status) VALUES(?,?,?,'design',?,?,?,?,'pending')");$q->execute([$c['id'],$c['user_id'],$c['render_revision'],$offset,$base,$key,json_encode($options,JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE)]);return (int)$this->pdo->lastInsertId(); }
 public function designCount(int $clipId,int $userId): int { $q=$this->pdo->prepare("SELECT COUNT(*) FROM clip_thumbnails WHERE clip_id=? AND user_id=? AND kind='design'");$q->execute([$clipId,$userId]);return (int)$q->fetchColumn(); }
 public function jobContext(int $id,string $kind,int $projectId): ?array { $table=$kind==='set'?'clip_thumbnail_sets':'clip_thumbnails';$q=$this->pdo->prepare("SELECT * FROM $table WHERE id=?");$q->execute([$id]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r||$r['status']==='ready'||$r['status']==='failed')return null; $c=$this->sourceOwned((int)$r['clip_id'],(int)$r['user_id']);if(!$c||(int)$c['project_id']!==$projectId||(int)$r['render_revision']!==(int)$c['render_revision'])return null;return ['row'=>$r,'clip'=>$c]; }
 public function markFailed(int $id,string $kind): void { $table=$kind==='set'?'clip_thumbnail_sets':'clip_thumbnails';$q=$this->pdo->prepare("UPDATE $table SET status='failed',error_code='thumbnail_failed',updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='pending'");$q->execute([$id]); }
 /** Must be called inside the lease transaction; rows and artifact reservations commit together. */
 public function complete(int $id,string $kind,array $artifacts,int $projectId): void { $context=$this->jobContext($id,$kind,$projectId);if(!$context)throw new \RuntimeException('Thumbnail source changed.');$r=$context['row'];foreach($artifacts as $i=>$a) { if($kind==='set') { $q=$this->pdo->prepare("INSERT INTO clip_thumbnails(set_id,clip_id,user_id,render_revision,kind,candidate_index,offset_seconds,options_json,status,object_key,size_bytes,mime_type,width,height) VALUES(?,?,?,?,'candidate',?,?,'{}','ready',?,?,'image/jpeg',1280,720)");$q->execute([$id,$r['clip_id'],$r['user_id'],$r['render_revision'],$i,$a['offset'],$a['key'],$a['size']]); } else { $q=$this->pdo->prepare("UPDATE clip_thumbnails SET status='ready',object_key=?,size_bytes=?,mime_type='image/jpeg',width=1280,height=720,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='pending'");$q->execute([$a['key'],$a['size'],$id]); } } if($kind==='set') { $q=$this->pdo->prepare("UPDATE clip_thumbnail_sets SET status='ready',candidate_count=?,updated_at=CURRENT_TIMESTAMP WHERE id=?");$q->execute([count($artifacts),$id]); } }
}
